django.utils.autoreload INFO 2023-03-29 18:27:37,210 autoreload 28048 16796 Watching for file changes with StatReloader
django.server INFO 2023-03-29 18:27:40,208 basehttp 28048 2672 "GET / HTTP/1.1" 200 8727
django.server INFO 2023-03-29 18:27:40,289 basehttp 28048 2672 "GET /static/css/custom.css HTTP/1.1" 304 0
django.server INFO 2023-03-29 18:27:40,294 basehttp 28048 9796 "GET /static/js/editableTable.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 18:27:42,647 basehttp 28048 9796 "POST /accounts/login/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 18:27:43,129 basehttp 28048 9796 "GET /index/ HTTP/1.1" 200 15275
django.request ERROR 2023-03-29 18:27:46,155 log 28048 9796 Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 241, in get_context_data
    context['fields']=self.model.get_fields(fields=self.model_fields)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 267, in get_fields
    select_fields=[fields[f.name] for f in fields.keys()  if f.name in cls._meta.fields]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 267, in <listcomp>
    select_fields=[fields[f.name] for f in fields.keys()  if f.name in cls._meta.fields]
                                                             ^^^^^^
AttributeError: 'str' object has no attribute 'name'
django.server ERROR 2023-03-29 18:27:46,158 basehttp 28048 9796 "GET /organism_card HTTP/1.1" 500 106585
django.request WARNING 2023-03-29 18:27:46,436 log 28048 9796 Not Found: /favicon.ico
django.server WARNING 2023-03-29 18:27:46,436 basehttp 28048 9796 "GET /favicon.ico HTTP/1.1" 404 11785
django.utils.autoreload INFO 2023-03-29 18:32:05,635 autoreload 28048 16796 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 18:32:06,841 autoreload 15124 3992 Watching for file changes with StatReloader
django.request ERROR 2023-03-29 18:32:09,456 log 15124 17516 Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 241, in get_context_data
    context['fields']=self.model.get_fields(fields=self.model_fields)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 267, in get_fields
    select_fields=[fields[f.name] for f in fields.keys()  if f.name in cls._meta.fields]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 267, in <listcomp>
    select_fields=[fields[f.name] for f in fields.keys()  if f.name in cls._meta.fields]
                                                             ^^^^^^
AttributeError: 'str' object has no attribute 'name'
django.server ERROR 2023-03-29 18:32:09,458 basehttp 15124 17516 "GET /organism_card HTTP/1.1" 500 106597
django.utils.autoreload INFO 2023-03-29 18:36:29,663 autoreload 15124 3992 C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 18:36:30,853 autoreload 17892 29356 Watching for file changes with StatReloader
django.request ERROR 2023-03-29 18:36:44,433 log 17892 2232 Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 241, in get_context_data
    context['fields']=self.model.get_fields(fields=self.model_fields)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 267, in get_fields
    select_fields=[fields[f.name] for f in fields.keys()  if f.name in cls._meta.fields]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 267, in <listcomp>
    select_fields=[fields[f.name] for f in fields.keys()  if f.name in cls._meta.fields]
                                                             ^^^^^^
AttributeError: 'str' object has no attribute 'name'
django.server ERROR 2023-03-29 18:36:44,435 basehttp 17892 2232 "GET /organism_card HTTP/1.1" 500 106597
django.utils.autoreload INFO 2023-03-29 18:37:59,828 autoreload 17892 29356 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 18:38:00,967 autoreload 24932 13340 Watching for file changes with StatReloader
django.request ERROR 2023-03-29 18:38:05,740 log 24932 16520 Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 241, in get_context_data
    context['fields']=self.model.get_fields(fields=self.model_fields)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 267, in get_fields
    select_fields=[fields[f] for f in fields.keys()  if f.name in cls._meta.fields]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 267, in <listcomp>
    select_fields=[fields[f] for f in fields.keys()  if f.name in cls._meta.fields]
                                                        ^^^^^^
AttributeError: 'str' object has no attribute 'name'
django.server ERROR 2023-03-29 18:38:05,743 basehttp 24932 16520 "GET /organism_card HTTP/1.1" 500 106577
django.utils.autoreload INFO 2023-03-29 18:41:27,414 autoreload 24932 13340 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 18:41:28,495 autoreload 23428 10340 Watching for file changes with StatReloader
django.server INFO 2023-03-29 18:41:35,553 basehttp 23428 24776 "GET / HTTP/1.1" 302 0
django.server INFO 2023-03-29 18:41:36,005 basehttp 23428 24776 "GET /index/ HTTP/1.1" 200 15275
django.server INFO 2023-03-29 18:41:36,034 basehttp 23428 24776 "GET /static/css/custom.css HTTP/1.1" 304 0
django.server INFO 2023-03-29 18:41:36,035 basehttp 23428 15984 "GET /static/js/editableTable.js HTTP/1.1" 304 0
django.request ERROR 2023-03-29 18:41:38,797 log 23428 15984 Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 241, in get_context_data
    context['fields']=self.model.get_fields(fields=self.model_fields)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 267, in get_fields
    select_fields=[fields[cls._meta.fields.f] for f in fields.keys()  if f in cls._meta.fields.keys()]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 267, in <listcomp>
    select_fields=[fields[cls._meta.fields.f] for f in fields.keys()  if f in cls._meta.fields.keys()]
                                                                              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ImmutableList' object has no attribute 'keys'
django.server ERROR 2023-03-29 18:41:38,799 basehttp 23428 15984 "GET /organism_card HTTP/1.1" 500 106713
django.utils.autoreload INFO 2023-03-29 18:52:44,646 autoreload 23428 10340 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 18:52:45,830 autoreload 26708 1360 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 19:00:48,248 autoreload 26708 1360 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:00:49,378 autoreload 17520 14084 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 19:01:48,238 autoreload 17520 14084 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:01:49,322 autoreload 13592 17896 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:01:55,533 basehttp 13592 18644 "GET / HTTP/1.1" 302 0
django.server INFO 2023-03-29 19:01:55,985 basehttp 13592 18644 "GET /index/ HTTP/1.1" 200 15275
django.server INFO 2023-03-29 19:01:56,012 basehttp 13592 18644 "GET /static/css/custom.css HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:01:56,020 basehttp 13592 20632 "GET /static/js/editableTable.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:01:56,102 basehttp 13592 5336 "GET /static/js/sorting_table.js HTTP/1.1" 200 877
django.request ERROR 2023-03-29 19:01:58,633 log 13592 5336 Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 241, in get_context_data
    context['fields']=self.model.get_fields(fields=self.model_fields)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 262, in get_fields
    select_fields=[fields.f for f in fields.keys() if f in fieldsname]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 262, in <listcomp>
    select_fields=[fields.f for f in fields.keys() if f in fieldsname]
                   ^^^^^^^^
AttributeError: 'dict' object has no attribute 'f'
django.server ERROR 2023-03-29 19:01:58,635 basehttp 13592 5336 "GET /organism_card HTTP/1.1" 500 108331
django.utils.autoreload INFO 2023-03-29 19:02:10,508 autoreload 13592 17896 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:02:11,703 autoreload 2416 3184 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:02:14,494 basehttp 2416 27552 "GET /organism_card HTTP/1.1" 200 156961
django.server INFO 2023-03-29 19:02:25,548 basehttp 2416 27552 "GET /organism_list HTTP/1.1" 200 92427
django.utils.autoreload INFO 2023-03-29 19:03:35,038 autoreload 2416 3184 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:03:36,129 autoreload 18440 11000 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:03:43,776 basehttp 18440 20652 "GET /organism_list HTTP/1.1" 200 92427
django.server INFO 2023-03-29 19:08:51,968 basehttp 18440 29608 "GET /organism_list HTTP/1.1" 200 92427
django.utils.autoreload INFO 2023-03-29 19:11:08,958 autoreload 18440 11000 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:11:10,138 autoreload 20740 27956 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 19:11:24,316 autoreload 20740 27956 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:11:25,481 autoreload 18260 24064 Watching for file changes with StatReloader
django.request ERROR 2023-03-29 19:11:31,821 log 18260 4216 Internal Server Error: /organism_list
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 715, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 847, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\template\base.py", line 914, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py", line 297, in get_values
    return value_listv
          ^^^^^^^^^^^
NameError: name 'value_listv' is not defined
django.server ERROR 2023-03-29 19:11:31,825 basehttp 18260 4216 "GET /organism_list HTTP/1.1" 500 308144
django.utils.autoreload INFO 2023-03-29 19:11:50,889 autoreload 18260 24064 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:11:52,075 autoreload 23628 23920 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:11:56,806 basehttp 23628 22108 "GET /organism_list HTTP/1.1" 200 92427
django.server INFO 2023-03-29 19:12:11,967 basehttp 23628 22108 "GET /createOrg/ HTTP/1.1" 200 16412
django.server INFO 2023-03-29 19:12:31,270 basehttp 23628 22108 "GET /organism/FG_0001 HTTP/1.1" 200 50659
django.server INFO 2023-03-29 19:12:31,400 basehttp 23628 22108 "GET /static/js/editablerow_stock.js HTTP/1.1" 200 1808
django.server INFO 2023-03-29 19:12:38,681 basehttp 23628 22108 "GET /organism/FG_0001 HTTP/1.1" 200 50659
django.server INFO 2023-03-29 19:12:48,838 basehttp 23628 22108 "GET /stocklist/FG_0001_03?Batch_id=FG_0001_03&_=1680081158695 HTTP/1.1" 200 12
django.server INFO 2023-03-29 19:12:51,518 basehttp 23628 22108 "GET /stocklist/FG_0001_01?Batch_id=FG_0001_01&_=1680081158696 HTTP/1.1" 200 838
django.server INFO 2023-03-29 19:12:57,025 basehttp 23628 22108 "GET /organism/updateStock/3476 HTTP/1.1" 200 8968
django.server INFO 2023-03-29 19:14:19,517 basehttp 23628 22108 "GET /index/ HTTP/1.1" 200 15275
django.server INFO 2023-03-29 19:14:23,229 basehttp 23628 22108 "GET /organism_card HTTP/1.1" 200 156961
django.server INFO 2023-03-29 19:14:28,823 basehttp 23628 22108 "GET /taxonomy_card HTTP/1.1" 200 257263
django.server INFO 2023-03-29 19:14:31,123 basehttp 23628 22108 "GET /taxonomy/Aa-colombiana HTTP/1.1" 200 21688
django.server INFO 2023-03-29 19:14:45,404 basehttp 23628 22108 "GET /organism_card HTTP/1.1" 200 156961
django.server INFO 2023-03-29 19:14:45,421 basehttp 23628 3400 "GET /static/js/sorting_table.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:14:45,422 basehttp 23628 22108 "GET /static/css/custom.css HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:14:45,422 basehttp 23628 24552 "GET /static/js/editableTable.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:14:54,301 basehttp 23628 24552 "GET /organism_card?paginate_by=50&order_by=&substructure=&Class=GP&ID=&Name=&Strain=&Notes=&MTA= HTTP/1.1" 200 156489
django.server INFO 2023-03-29 19:14:59,080 basehttp 23628 24552 "GET /organism_card?paginate_by=50&order_by=&substructure=&ID=&Name=&Strain=&Notes=&MTA= HTTP/1.1" 200 157466
django.server INFO 2023-03-29 19:15:11,047 basehttp 23628 24552 "GET /organism_card?paginate_by=50&order_by=&substructure=&Class=GP&ID=&Name=&Strain=&Notes=test&MTA= HTTP/1.1" 200 34764
django.server INFO 2023-03-29 19:15:14,571 basehttp 23628 24552 "GET /organism_card?paginate_by=50&order_by=&substructure=&ID=&Name=&Strain=&Notes=&MTA= HTTP/1.1" 200 157466
django.server INFO 2023-03-29 19:21:45,734 basehttp 23628 1484 "GET /organism_card?paginate_by=50&order_by=&substructure=&ID=&Name=&Strain=&Notes=&MTA= HTTP/1.1" 200 157466
django.utils.autoreload INFO 2023-03-29 19:21:56,025 autoreload 23628 23920 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:21:57,119 autoreload 19348 4192 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 19:24:28,631 autoreload 19348 4192 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:24:29,713 autoreload 2620 29684 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 19:26:06,279 autoreload 2620 29684 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:26:07,378 autoreload 24608 26472 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:26:48,102 basehttp 24608 11952 "GET /organism_card?paginate_by=50&order_by=&substructure=&ID=&Name=&Strain=&Notes=&MTA= HTTP/1.1" 200 157466
django.utils.autoreload INFO 2023-03-29 19:28:07,476 autoreload 24608 26472 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:28:08,569 autoreload 23152 8744 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 19:28:22,535 autoreload 23152 8744 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:28:23,590 autoreload 4188 16952 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:31:25,564 basehttp 4188 16024 "GET /organism_card?paginate_by=50&order_by=&substructure=&ID=&Name=&Strain=&Notes=&MTA= HTTP/1.1" 200 157481
django.server INFO 2023-03-29 19:31:25,584 basehttp 4188 15648 "GET /static/js/sorting_table.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:31:25,584 basehttp 4188 16024 "GET /static/css/custom.css HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:31:25,585 basehttp 4188 27496 "GET /static/js/editableTable.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:31:36,153 basehttp 4188 27496 "POST /exportData/ HTTP/1.1" 200 27
django.server INFO 2023-03-29 19:32:33,159 basehttp 4188 27496 "GET /index/ HTTP/1.1" 200 15275
django.server INFO 2023-03-29 19:32:37,354 basehttp 4188 27496 "GET /organism_card HTTP/1.1" 200 156976
django.server INFO 2023-03-29 19:32:42,022 basehttp 4188 27496 "GET /createOrg/ HTTP/1.1" 200 16412
django.server INFO 2023-03-29 19:32:47,156 basehttp 4188 27496 "POST /search_organism/ HTTP/1.1" 200 470
django.server INFO 2023-03-29 19:33:30,878 basehttp 4188 27496 "POST /createOrg/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 19:33:32,607 basehttp 4188 27496 "GET /organism_card HTTP/1.1" 200 156976
django.server INFO 2023-03-29 19:33:41,349 basehttp 4188 27496 "GET /organism_card?paginate_by=50&order_by=&substructure=&Class=&ID=&Name=test&Strain=&Notes=&MTA= HTTP/1.1" 200 34746
django.server INFO 2023-03-29 19:34:02,445 basehttp 4188 27496 "GET /organism/FG_0089 HTTP/1.1" 200 44431
django.server INFO 2023-03-29 19:34:02,491 basehttp 4188 27496 "GET /static/js/editablerow_stock.js HTTP/1.1" 304 0
django.request ERROR 2023-03-29 19:34:09,166 log 4188 27496 Internal Server Error: /createBatch/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py", line 247, in createBatch
    form=Batch_form()
         ^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py", line 81, in __init__
    self.fields['qc_status'].choices=[(obj.dict_value, obj.strtml()) for obj in Dictionary.objects.filter(dict_class=Organism.Choice_Dictionary['qc_status'], astatus__gte=0)]
                                                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'qc_status'
django.server ERROR 2023-03-29 19:34:09,166 basehttp 4188 27496 "GET /createBatch/ HTTP/1.1" 500 85744
django.utils.autoreload INFO 2023-03-29 19:37:14,067 autoreload 4188 16952 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:37:15,285 autoreload 10808 8996 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:37:20,279 basehttp 10808 19272 "GET /organism/FG_0089 HTTP/1.1" 200 44431
django.server INFO 2023-03-29 19:37:27,624 basehttp 10808 19272 "POST /updateOrg/FG_0089 HTTP/1.1" 302 0
django.server INFO 2023-03-29 19:37:28,505 basehttp 10808 19272 "GET /organism/FG_0089 HTTP/1.1" 200 44700
django.server INFO 2023-03-29 19:37:31,676 basehttp 10808 19272 "GET /createBatch/ HTTP/1.1" 200 9955
django.server INFO 2023-03-29 19:37:31,757 basehttp 10808 19272 "GET /static/js/search_organism_id.js HTTP/1.1" 200 1842
django.server INFO 2023-03-29 19:37:37,552 basehttp 10808 19272 "POST /search_organism_id/ HTTP/1.1" 200 1879
django.server INFO 2023-03-29 19:37:37,993 basehttp 10808 19272 "POST /search_organism_id/ HTTP/1.1" 200 1879
django.server INFO 2023-03-29 19:38:21,722 basehttp 10808 19272 "POST /createBatch/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 19:38:22,638 basehttp 10808 19272 "GET /organism/FG_0089 HTTP/1.1" 200 46744
django.server INFO 2023-03-29 19:38:33,031 basehttp 10808 19272 "GET /stocklist/FG_0089_01?Batch_id=FG_0089_01&_=1680082702665 HTTP/1.1" 200 12
django.server INFO 2023-03-29 19:38:34,568 basehttp 10808 19272 "GET /createStock/ HTTP/1.1" 200 103197
django.server INFO 2023-03-29 19:39:05,692 basehttp 10808 19272 "POST /createStock/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 19:39:06,627 basehttp 10808 19272 "GET /organism/FG_0089 HTTP/1.1" 200 46744
django.server INFO 2023-03-29 19:39:08,930 basehttp 10808 19272 "GET /stocklist/FG_0089_01?Batch_id=FG_0089_01&_=1680082746655 HTTP/1.1" 200 12
django.request ERROR 2023-03-29 19:39:17,023 log 10808 19272 Internal Server Error: /updateBat/FG_0089_01
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py", line 276, in updateBatch
    form=Batchupdate_form(instance=object_)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py", line 104, in __init__
    super(Batch_form, self).__init__(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: super(type, obj): obj must be an instance or subtype of type
django.server ERROR 2023-03-29 19:39:17,039 basehttp 10808 19272 "GET /updateBat/FG_0089_01 HTTP/1.1" 500 86737
django.request ERROR 2023-03-29 19:39:19,044 log 10808 19272 Internal Server Error: /updateBat/FG_0089_01
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py", line 276, in updateBatch
    form=Batchupdate_form(instance=object_)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py", line 104, in __init__
    super(Batch_form, self).__init__(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: super(type, obj): obj must be an instance or subtype of type
django.server ERROR 2023-03-29 19:39:19,044 basehttp 10808 19272 "GET /updateBat/FG_0089_01 HTTP/1.1" 500 86737
django.utils.autoreload INFO 2023-03-29 19:40:36,162 autoreload 10808 8996 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:40:37,286 autoreload 1952 25448 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:41:08,491 basehttp 1952 8980 "GET /updateBat/FG_0089_01 HTTP/1.1" 200 7378
django.server INFO 2023-03-29 19:41:14,854 basehttp 1952 8980 "GET /organism/FG_0089 HTTP/1.1" 200 46744
django.server INFO 2023-03-29 19:41:22,234 basehttp 1952 8980 "GET /updateBat/FG_0089_01 HTTP/1.1" 200 7378
django.utils.autoreload INFO 2023-03-29 19:45:25,854 autoreload 1952 25448 C:\Users\uqwzhon4\project\adjCOADD\apputil\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:45:27,124 autoreload 27004 7804 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:46:26,622 basehttp 27004 21964 "GET /organism/FG_0089 HTTP/1.1" 200 46744
django.utils.autoreload INFO 2023-03-29 19:51:00,087 autoreload 27004 7804 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:51:01,278 autoreload 28892 10888 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 19:52:53,742 autoreload 25156 21160 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:53:21,215 basehttp 25156 1008 "GET /organism/FG_0089 HTTP/1.1" 200 46744
django.server INFO 2023-03-29 19:53:21,246 basehttp 25156 1008 "GET /static/css/custom.css HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:53:21,251 basehttp 25156 836 "GET /static/js/sorting_table.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:53:21,254 basehttp 25156 1008 "GET /static/js/editableTable.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:53:21,310 basehttp 25156 1008 "GET /static/js/editablerow_stock.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 19:53:27,225 basehttp 25156 1008 "GET /createBatch/ HTTP/1.1" 200 9955
django.server INFO 2023-03-29 19:53:31,432 basehttp 25156 1008 "POST /search_organism_id/ HTTP/1.1" 200 1879
django.server INFO 2023-03-29 19:53:31,680 basehttp 25156 836 "POST /search_organism_id/ HTTP/1.1" 200 1879
django.server INFO 2023-03-29 19:53:34,171 basehttp 25156 836 "POST /search_organism_id/ HTTP/1.1" 200 1879
django.server INFO 2023-03-29 19:53:34,230 basehttp 25156 1008 "POST /search_organism_id/ HTTP/1.1" 200 1879
django.server INFO 2023-03-29 19:53:34,659 basehttp 25156 1008 "POST /search_organism_id/ HTTP/1.1" 200 1879
django.server INFO 2023-03-29 19:53:34,757 basehttp 25156 836 "POST /search_organism_id/ HTTP/1.1" 200 1879
django.server INFO 2023-03-29 19:53:34,995 basehttp 25156 16972 "POST /search_organism_id/ HTTP/1.1" 200 220
django.server INFO 2023-03-29 19:53:35,424 basehttp 25156 16972 "POST /search_organism_id/ HTTP/1.1" 200 31
django.server INFO 2023-03-29 19:53:50,536 basehttp 25156 16972 "POST /createBatch/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 19:53:51,507 basehttp 25156 16972 "GET /organism/FG_0089 HTTP/1.1" 200 48788
django.server INFO 2023-03-29 19:54:01,214 basehttp 25156 16972 "GET /updateBat/FG_0089_01 HTTP/1.1" 200 7461
django.server INFO 2023-03-29 19:54:26,059 basehttp 25156 16972 "GET /organism/FG_0089 HTTP/1.1" 200 48788
django.server INFO 2023-03-29 19:54:29,430 basehttp 25156 16972 "GET /updateBat/FG_0089_01 HTTP/1.1" 200 14227
django.server INFO 2023-03-29 19:55:44,031 basehttp 25156 16972 "GET /organism/FG_0089 HTTP/1.1" 200 48788
django.server INFO 2023-03-29 19:55:46,802 basehttp 25156 16972 "GET /updateBat/FG_0089_01 HTTP/1.1" 200 7362
django.request ERROR 2023-03-29 19:55:55,914 log 25156 16972 Internal Server Error: /updateBat/FG_0089_01
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py", line 283, in updateBatch
    print(qd["orgbatch_id"])
          ~~^^^^^^^^^^^^^^^
KeyError: 'orgbatch_id'
django.server ERROR 2023-03-29 19:55:55,914 basehttp 25156 16972 "PUT /updateBat/FG_0089_01 HTTP/1.1" 500 82956
django.utils.autoreload INFO 2023-03-29 19:56:19,989 autoreload 25156 21160 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 19:56:21,144 autoreload 26560 14444 Watching for file changes with StatReloader
django.server INFO 2023-03-29 19:57:17,672 basehttp 26560 26680 "GET /organism/FG_0089 HTTP/1.1" 200 48788
django.server INFO 2023-03-29 19:57:20,576 basehttp 26560 26680 "GET /updateBat/FG_0089_01 HTTP/1.1" 200 7378
django.server INFO 2023-03-29 19:57:27,054 basehttp 26560 26680 "PUT /updateBat/FG_0089_01 HTTP/1.1" 200 2010
django.server INFO 2023-03-29 19:57:45,879 basehttp 26560 26680 "GET /stocklist/FG_0089_02?Batch_id=FG_0089_02&_=1680083837702 HTTP/1.1" 200 12
django.server INFO 2023-03-29 19:59:42,150 basehttp 26560 26680 "POST /deleteBat/FG_0089_01 HTTP/1.1" 302 0
django.server INFO 2023-03-29 19:59:43,042 basehttp 26560 26680 "GET /organism/FG_0089 HTTP/1.1" 200 46744
django.server INFO 2023-03-29 19:59:46,066 basehttp 26560 26680 "GET /stocklist/FG_0089_02?Batch_id=FG_0089_02&_=1680083983064 HTTP/1.1" 200 12
django.server INFO 2023-03-29 19:59:49,744 basehttp 26560 26680 "GET /updateBat/FG_0089_02 HTTP/1.1" 200 7378
django.server INFO 2023-03-29 19:59:54,786 basehttp 26560 26680 "PUT /updateBat/FG_0089_02 HTTP/1.1" 200 2010
django.server INFO 2023-03-29 20:00:00,127 basehttp 26560 26680 "GET /createStock/ HTTP/1.1" 200 103197
django.server INFO 2023-03-29 20:00:59,689 basehttp 26560 26680 "POST /createStock/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 20:01:00,623 basehttp 26560 26680 "GET /organism/FG_0089 HTTP/1.1" 200 46748
django.server INFO 2023-03-29 20:01:03,335 basehttp 26560 26680 "GET /stocklist/FG_0089_02?Batch_id=FG_0089_02&_=1680084060646 HTTP/1.1" 200 12
django.server INFO 2023-03-29 20:03:11,612 basehttp 26560 26680 "GET /createStock/ HTTP/1.1" 200 103197
django.server INFO 2023-03-29 20:04:28,336 basehttp 26560 26680 "GET /organism/FG_0089 HTTP/1.1" 200 46744
django.server INFO 2023-03-29 20:04:30,655 basehttp 26560 26680 "GET /stocklist/FG_0089_02?Batch_id=FG_0089_02&_=1680084268366 HTTP/1.1" 200 12
django.server INFO 2023-03-29 20:04:32,829 basehttp 26560 26680 "GET /createStock/ HTTP/1.1" 200 103197
django.server INFO 2023-03-29 20:05:37,738 basehttp 26560 26680 "GET /organism/FG_0089 HTTP/1.1" 200 46763
django.server INFO 2023-03-29 20:05:39,951 basehttp 26560 26680 "GET /stocklist/FG_0089_02?Batch_id=FG_0089_02&_=1680084337767 HTTP/1.1" 200 12
django.server INFO 2023-03-29 20:05:41,757 basehttp 26560 26680 "GET /createStock/ HTTP/1.1" 200 103197
django.server INFO 2023-03-29 20:06:22,751 basehttp 26560 26680 "POST /createStock/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 20:06:23,665 basehttp 26560 26680 "GET /organism/FG_0089 HTTP/1.1" 200 46763
django.server INFO 2023-03-29 20:06:26,471 basehttp 26560 26680 "GET /stocklist/FG_0089_02?Batch_id=FG_0089_02&_=1680084383692 HTTP/1.1" 200 12
django.utils.autoreload INFO 2023-03-29 20:08:25,773 autoreload 26560 14444 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:08:26,980 autoreload 13900 19620 Watching for file changes with StatReloader
django.server INFO 2023-03-29 20:08:34,220 basehttp 13900 20164 "GET /createStock/ HTTP/1.1" 200 102964
django.server INFO 2023-03-29 20:09:07,045 basehttp 13900 20164 "POST /createStock/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 20:09:07,990 basehttp 13900 20164 "GET /organism/FG_0089 HTTP/1.1" 200 46763
django.utils.autoreload INFO 2023-03-29 20:13:15,700 autoreload 13900 19620 C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:13:16,904 autoreload 25096 16692 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 20:13:25,576 autoreload 25096 16692 C:\Users\uqwzhon4\project\adjCOADD\dorganism\models.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:13:26,630 autoreload 23432 2548 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 20:14:18,387 autoreload 23432 2548 C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:14:19,404 autoreload 8384 12588 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 20:14:43,890 autoreload 8384 12588 C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:14:44,881 autoreload 18052 676 Watching for file changes with StatReloader
django.server INFO 2023-03-29 20:14:50,587 basehttp 18052 11432 "GET /organism/FG_0089 HTTP/1.1" 200 46763
django.server INFO 2023-03-29 20:14:50,615 basehttp 18052 11432 "GET /static/css/custom.css HTTP/1.1" 304 0
django.server INFO 2023-03-29 20:14:50,616 basehttp 18052 3332 "GET /static/js/sorting_table.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 20:14:50,619 basehttp 18052 16552 "GET /static/js/editableTable.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 20:14:50,648 basehttp 18052 16552 "GET /static/js/editablerow_stock.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 20:14:54,683 basehttp 18052 16552 "GET /stocklist/FG_0089_02?Batch_id=FG_0089_02&_=1680084890645 HTTP/1.1" 200 12
django.server INFO 2023-03-29 20:14:56,589 basehttp 18052 16552 "GET /createStock/ HTTP/1.1" 200 102964
django.server INFO 2023-03-29 20:15:22,147 basehttp 18052 16552 "POST /createStock/ HTTP/1.1" 200 102964
django.server INFO 2023-03-29 20:15:58,792 basehttp 18052 16552 "GET /createStock/ HTTP/1.1" 200 102964
django.server INFO 2023-03-29 20:16:06,493 basehttp 18052 16552 "GET /stocklist/FG_0089_02?Batch_id=FG_0089_02&_=1680084890646 HTTP/1.1" 200 12
django.utils.autoreload INFO 2023-03-29 20:21:23,476 autoreload 18052 676 C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:21:25,107 autoreload 6612 12696 Watching for file changes with StatReloader
django.server INFO 2023-03-29 20:21:31,579 basehttp 6612 19408 "GET /createCulture/ HTTP/1.1" 200 10778
django.server INFO 2023-03-29 20:21:31,587 basehttp 6612 19408 "GET /static/js/search_organism_id.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 20:21:35,182 basehttp 6612 19408 "POST /search_organism_id/ HTTP/1.1" 200 1879
django.server INFO 2023-03-29 20:21:35,464 basehttp 6612 20720 "POST /search_organism_id/ HTTP/1.1" 200 1879
django.server INFO 2023-03-29 20:21:53,580 basehttp 6612 20720 "POST /createCulture/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 20:21:54,674 basehttp 6612 20720 "GET /organism/FG_0089 HTTP/1.1" 200 48691
django.request ERROR 2023-03-29 20:22:02,627 log 6612 20720 Internal Server Error: /updateCulture/2
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py", line 484, in updateCulture
    form=Cultureupdate_form(instance=object_)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py", line 169, in __init__
    self.fields['culture_type'].choices=[(obj.dict_value, obj.strtml()) for obj in Dictionary.objects.filter(dict_class=Organism_Culture.Choice_Dictionary['culture_type'], astatus__gte=0)]
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'culture_type'
django.server ERROR 2023-03-29 20:22:02,643 basehttp 6612 20720 "GET /updateCulture/2 HTTP/1.1" 500 86574
django.request ERROR 2023-03-29 20:22:05,823 log 6612 20720 Internal Server Error: /updateCulture/2
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py", line 484, in updateCulture
    form=Cultureupdate_form(instance=object_)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py", line 169, in __init__
    self.fields['culture_type'].choices=[(obj.dict_value, obj.strtml()) for obj in Dictionary.objects.filter(dict_class=Organism_Culture.Choice_Dictionary['culture_type'], astatus__gte=0)]
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'culture_type'
django.server ERROR 2023-03-29 20:22:05,831 basehttp 6612 20720 "GET /updateCulture/2 HTTP/1.1" 500 86574
django.utils.autoreload INFO 2023-03-29 20:23:39,349 autoreload 6612 12696 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:23:41,626 autoreload 22532 25176 Watching for file changes with StatReloader
django.server INFO 2023-03-29 20:23:45,775 basehttp 22532 6416 "GET /updateCulture/2 HTTP/1.1" 200 101967
django.server INFO 2023-03-29 20:23:50,248 basehttp 22532 6416 "PUT /updateCulture/2 HTTP/1.1" 200 1894
django.server INFO 2023-03-29 20:23:55,054 basehttp 22532 6416 "GET /updateBat/FG_0089_02 HTTP/1.1" 200 7378
django.server INFO 2023-03-29 20:23:57,682 basehttp 22532 6416 "GET /organism/FG_0089 HTTP/1.1" 200 48695
django.server INFO 2023-03-29 20:24:09,871 basehttp 22532 6416 "GET /taxonomy_card HTTP/1.1" 200 257278
django.server INFO 2023-03-29 20:24:12,146 basehttp 22532 6416 "GET /taxonomy/Aa HTTP/1.1" 200 22336
django.server INFO 2023-03-29 20:24:18,450 basehttp 22532 6416 "GET /taxonomy_card HTTP/1.1" 200 257278
django.server INFO 2023-03-29 20:24:29,330 basehttp 22532 6416 "GET /taxonomy/Aa HTTP/1.1" 200 22336
django.server INFO 2023-03-29 20:24:38,899 basehttp 22532 6416 "POST /taxonomy/Aa HTTP/1.1" 200 22336
django.server INFO 2023-03-29 20:25:04,961 basehttp 22532 6416 "GET /taxonomy_card HTTP/1.1" 200 257278
django.server INFO 2023-03-29 20:25:16,818 basehttp 22532 6416 "GET /taxonomy_list HTTP/1.1" 200 178911
django.server INFO 2023-03-29 20:26:28,602 basehttp 22532 6416 "GET /taxonomy_list HTTP/1.1" 200 178911
django.server INFO 2023-03-29 20:26:55,689 basehttp 22532 6416 "GET /taxonomy_list HTTP/1.1" 200 178911
django.utils.autoreload INFO 2023-03-29 20:28:33,260 autoreload 22532 25176 C:\Users\uqwzhon4\project\adjCOADD\dorganism\utils.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:28:35,087 autoreload 12696 28252 Watching for file changes with StatReloader
django.server INFO 2023-03-29 20:28:38,993 basehttp 12696 21420 "GET /taxonomy/Aa HTTP/1.1" 200 22336
django.server INFO 2023-03-29 20:28:49,108 basehttp 12696 21420 "POST /taxonomy/Aa HTTP/1.1" 200 22336
django.server INFO 2023-03-29 20:29:05,108 basehttp 12696 21420 "GET /taxonomy_card HTTP/1.1" 200 257278
django.server INFO 2023-03-29 20:29:13,244 basehttp 12696 21420 "GET /taxonomy_list HTTP/1.1" 200 178911
django.utils.autoreload INFO 2023-03-29 20:29:59,346 autoreload 12696 28252 C:\Users\uqwzhon4\project\adjCOADD\dorganism\views.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:30:01,329 autoreload 28088 26500 Watching for file changes with StatReloader
django.server INFO 2023-03-29 20:30:03,627 basehttp 28088 11272 "GET /taxonomy/Aa HTTP/1.1" 200 22336
django.server INFO 2023-03-29 20:30:11,002 basehttp 28088 11272 "POST /taxonomy/Aa HTTP/1.1" 200 22336
django.server INFO 2023-03-29 20:30:40,785 basehttp 28088 11272 "GET /taxonomy_card HTTP/1.1" 200 257278
django.server INFO 2023-03-29 20:30:48,512 basehttp 28088 11272 "GET /taxonomy_list HTTP/1.1" 200 178911
django.server INFO 2023-03-29 20:31:42,620 basehttp 28088 11272 "GET /taxonomy/Aa-calceata HTTP/1.1" 200 22502
django.server INFO 2023-03-29 20:31:51,682 basehttp 28088 11272 "GET /taxonomy_card HTTP/1.1" 200 257278
django.server INFO 2023-03-29 20:31:54,539 basehttp 28088 11272 "GET /drug_card HTTP/1.1" 200 244425
django.server WARNING 2023-03-29 20:31:54,695 basehttp 28088 11272 "GET /static/images/AMD00002.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,720 basehttp 28088 6544 "GET /static/images/AMD00003.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,752 basehttp 28088 28816 "GET /static/images/AMD00004.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,804 basehttp 28088 24940 "GET /static/images/AMD00005.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,805 basehttp 28088 17856 "GET /static/images/AMD00006.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,828 basehttp 28088 964 "GET /static/images/AMD00007.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,837 basehttp 28088 8336 "GET /static/images/AMD00008.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,861 basehttp 28088 18072 "GET /static/images/AMD00009.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,865 basehttp 28088 21892 "GET /static/images/AMD00178.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,887 basehttp 28088 27016 "GET /static/images/AMD00011.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,912 basehttp 28088 24296 "GET /static/images/AMD00010.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,912 basehttp 28088 27504 "GET /static/images/AMD00012.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,952 basehttp 28088 692 "GET /static/images/AMD00013.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,961 basehttp 28088 20160 "GET /static/images/AMD00219.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,969 basehttp 28088 24496 "GET /static/images/AMD00216.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,980 basehttp 28088 23572 "GET /static/images/AMD00179.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:54,991 basehttp 28088 26896 "GET /static/images/AMD00014.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,014 basehttp 28088 16548 "GET /static/images/AMD00015.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,050 basehttp 28088 21196 "GET /static/images/AMD00017.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,058 basehttp 28088 8612 "GET /static/images/AMD00018.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,061 basehttp 28088 10640 "GET /static/images/AMD00016.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,073 basehttp 28088 1256 "GET /static/images/AMD00019.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,078 basehttp 28088 6532 "GET /static/images/AMD00020.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,098 basehttp 28088 6100 "GET /static/images/AMD00021.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,133 basehttp 28088 18364 "GET /static/images/AMD00022.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,144 basehttp 28088 28800 "GET /static/images/AMD00023.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,148 basehttp 28088 23944 "GET /static/images/AMD00024.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,180 basehttp 28088 956 "GET /static/images/AMD00025.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,180 basehttp 28088 25136 "GET /static/images/AMD00026.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,211 basehttp 28088 27140 "GET /static/images/AMD00028.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,219 basehttp 28088 16412 "GET /static/images/AMD00027.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,238 basehttp 28088 1136 "GET /static/images/AMD00029.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,256 basehttp 28088 7848 "GET /static/images/AMD00030.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,257 basehttp 28088 9512 "GET /static/images/AMD00031.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,262 basehttp 28088 13556 "GET /static/images/AMD00032.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:31:55,265 basehttp 28088 9380 "GET /static/images/AMD00033.svg HTTP/1.1" 404 1917
django.server INFO 2023-03-29 20:31:56,943 basehttp 28088 28832 "GET /drug/AMD00002 HTTP/1.1" 200 28759
django.server WARNING 2023-03-29 20:31:57,013 basehttp 28088 28832 "GET /static/images/AMD00002.svg HTTP/1.1" 404 1917
django.server INFO 2023-03-29 20:32:11,920 basehttp 28088 22492 "POST /updateDrug/AMD00002 HTTP/1.1" 302 0
django.server INFO 2023-03-29 20:32:12,471 basehttp 28088 22492 "GET /drug/AMD00002 HTTP/1.1" 200 28769
django.server WARNING 2023-03-29 20:32:12,570 basehttp 28088 22492 "GET /static/images/AMD00002.svg HTTP/1.1" 404 1917
django.server INFO 2023-03-29 20:32:27,441 basehttp 28088 1076 "GET /createDrug/ HTTP/1.1" 200 8209
django.server INFO 2023-03-29 20:32:49,201 basehttp 28088 1076 "POST /createDrug/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 20:32:49,866 basehttp 28088 1076 "GET /drug_card HTTP/1.1" 200 244711
django.server WARNING 2023-03-29 20:32:49,948 basehttp 28088 1076 "GET /static/images/AMD00002.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:49,960 basehttp 28088 22304 "GET /static/images/AMD00003.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,020 basehttp 28088 15424 "GET /static/images/AMD00004.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,023 basehttp 28088 17636 "GET /static/images/AMD00005.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,039 basehttp 28088 8072 "GET /static/images/AMD00006.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,050 basehttp 28088 18832 "GET /static/images/AMD00007.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,084 basehttp 28088 5168 "GET /static/images/AMD00010.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,084 basehttp 28088 21656 "GET /static/images/AMD00008.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,087 basehttp 28088 18360 "GET /static/images/AMD00178.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,091 basehttp 28088 27548 "GET /static/images/AMD00009.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,105 basehttp 28088 5660 "GET /static/images/AMD00011.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,136 basehttp 28088 26796 "GET /static/images/AMD00012.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,147 basehttp 28088 23656 "GET /static/images/AMD00216.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,159 basehttp 28088 23240 "GET /static/images/AMD00013.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,179 basehttp 28088 15768 "GET /static/images/AMD00219.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,197 basehttp 28088 14360 "GET /static/images/AMD00179.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,218 basehttp 28088 13276 "GET /static/images/AMD00014.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,218 basehttp 28088 22032 "GET /static/images/AMD00015.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,218 basehttp 28088 18476 "GET /static/images/AMD00016.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,238 basehttp 28088 18704 "GET /static/images/AMD00017.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,248 basehttp 28088 15792 "GET /static/images/AMD00019.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,262 basehttp 28088 26044 "GET /static/images/AMD00018.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,264 basehttp 28088 24400 "GET /static/images/AMD00021.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,288 basehttp 28088 27332 "GET /static/images/AMD00020.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,311 basehttp 28088 15452 "GET /static/images/AMD00023.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,313 basehttp 28088 19856 "GET /static/images/AMD00022.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,335 basehttp 28088 5848 "GET /static/images/AMD00024.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,349 basehttp 28088 8808 "GET /static/images/AMD00025.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,353 basehttp 28088 16216 "GET /static/images/AMD00026.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,363 basehttp 28088 21432 "GET /static/images/AMD00027.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,397 basehttp 28088 20216 "GET /static/images/AMD00028.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,398 basehttp 28088 23800 "GET /static/images/AMD00029.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,414 basehttp 28088 7780 "GET /static/images/AMD00031.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,414 basehttp 28088 10716 "GET /static/images/AMD00030.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,416 basehttp 28088 17616 "GET /static/images/AMD00033.svg HTTP/1.1" 404 1917
django.server WARNING 2023-03-29 20:32:50,416 basehttp 28088 13928 "GET /static/images/AMD00032.svg HTTP/1.1" 404 1917
django.server INFO 2023-03-29 20:33:04,743 basehttp 28088 19216 "GET /organism_card HTTP/1.1" 200 156976
django.server INFO 2023-03-29 20:33:07,919 basehttp 28088 19216 "GET /organism/FG_0001 HTTP/1.1" 200 50674
django.utils.autoreload INFO 2023-03-29 20:36:30,330 autoreload 28088 26500 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:36:32,499 autoreload 18260 19572 Watching for file changes with StatReloader
django.utils.autoreload INFO 2023-03-29 20:36:39,834 autoreload 18260 19572 C:\Users\uqwzhon4\project\adjCOADD\dorganism\forms.py changed, reloading.
django.utils.autoreload INFO 2023-03-29 20:36:42,189 autoreload 21512 17200 Watching for file changes with StatReloader
django.server INFO 2023-03-29 20:37:52,099 basehttp 21512 27712 "GET /stocklist/FG_0001_01?Batch_id=FG_0001_01&_=1680085987987 HTTP/1.1" 200 838
django.server INFO 2023-03-29 20:37:57,365 basehttp 21512 27712 "GET /stocklist/FG_0001_03?Batch_id=FG_0001_03&_=1680085987988 HTTP/1.1" 200 12
django.server INFO 2023-03-29 20:38:10,910 basehttp 21512 27712 "GET /organism_card?paginate_by=50&order_by=&substructure=&Class=&ID=&Name=test&Strain=&Notes=&MTA= HTTP/1.1" 200 34720
django.server INFO 2023-03-29 20:38:10,965 basehttp 21512 18612 "GET /static/js/sorting_table.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 20:38:10,965 basehttp 21512 27712 "GET /static/css/custom.css HTTP/1.1" 304 0
django.server INFO 2023-03-29 20:38:10,972 basehttp 21512 5340 "GET /static/js/editableTable.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 20:38:15,009 basehttp 21512 5340 "GET /organism/FG_0089 HTTP/1.1" 200 48695
django.server INFO 2023-03-29 20:38:15,066 basehttp 21512 5340 "GET /static/js/editablerow_stock.js HTTP/1.1" 304 0
django.server INFO 2023-03-29 20:38:17,762 basehttp 21512 5340 "GET /stocklist/FG_0089_02?Batch_id=FG_0089_02&_=1680086295073 HTTP/1.1" 200 12
django.server INFO 2023-03-29 20:38:21,948 basehttp 21512 5340 "GET /createStock/ HTTP/1.1" 200 103197
django.server INFO 2023-03-29 20:39:06,001 basehttp 21512 5340 "POST /createStock/ HTTP/1.1" 302 0
django.server INFO 2023-03-29 20:39:07,066 basehttp 21512 5340 "GET /organism/FG_0089 HTTP/1.1" 200 48695
django.server INFO 2023-03-29 20:39:13,015 basehttp 21512 5340 "GET /stocklist/FG_0089_02?Batch_id=FG_0089_02&_=1680086347120 HTTP/1.1" 200 12
django.server INFO 2023-03-29 20:39:28,418 basehttp 21512 5340 "GET /organism_card?paginate_by=50&order_by=&substructure=&ID=&Name=&Strain=&Notes=&MTA= HTTP/1.1" 200 157481
django.server INFO 2023-03-29 20:39:46,995 basehttp 21512 5340 "GET /organism_card?paginate_by=50&order_by=&substructure=&Class=FG&ID=&Name=&Strain=&Notes=&MTA= HTTP/1.1" 200 156651
django.server INFO 2023-03-29 20:40:04,162 basehttp 21512 5340 "GET /organism_card?paginate_by=50&order_by=&substructure=&Class=FG&ID=FG_0001&Name=&Strain=&Notes=&MTA= HTTP/1.1" 200 32318
django.server INFO 2023-03-29 20:40:07,081 basehttp 21512 5340 "GET /organism/FG_0001 HTTP/1.1" 200 50674
django.server INFO 2023-03-29 20:40:10,693 basehttp 21512 5340 "GET /stocklist/FG_0001_01?Batch_id=FG_0001_01&_=1680086407101 HTTP/1.1" 200 838
