Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 248, in post
    print(f"cardlist is: {self.lCards[f]}")
                                      ^
UnboundLocalError: cannot access local variable 'f' where it is not associated with a value
"POST /import-VITEK/ HTTP/1.1" 500 91711
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 256, in post
    djCard=VITEK_Card.check_from_dict(e, self.vLog)
                                      ^
UnboundLocalError: cannot access local variable 'e' where it is not associated with a value
"POST /import-VITEK/ HTTP/1.1" 500 92612
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 336, in post
    self.lAst-{}
    ~~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'dict' and 'dict'
"POST /import-VITEK/ HTTP/1.1" 500 93079
Watching for file changes with StatReloader
"GET /import-VITEK/ HTTP/1.1" 200 10291
Watching for file changes with StatReloader
"POST /import-VITEK/ HTTP/1.1" 200 12382
"POST /import-VITEK/ HTTP/1.1" 200 3494
C:\Users\uqwzhon4\project\adjCOADD\ddrug\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /import-VITEK/ HTTP/1.1" 200 10291
"POST /import-VITEK/ HTTP/1.1" 200 12384
"POST /import-VITEK/ HTTP/1.1" 200 436
C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6587
"GET /static/js/jquery-3.6.1.min.js HTTP/1.1" 200 89664
"GET /static/js/sorting_table.js HTTP/1.1" 200 601
"GET /static/css/app.css HTTP/1.1" 200 117298
"GET /static/css/custom.css HTTP/1.1" 200 12384
"GET /static/images/brand/CO-ADD_Logo_White_NoBackground_CMYK.png HTTP/1.1" 200 2856
"POST /accounts/login/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 11234
"GET /static/images/app/avatar.png HTTP/1.1" 200 9371
"GET /static/images/brand/CO-ADD_Logo_White_NoBackground_Baseline1500x375.png HTTP/1.1" 200 26975
"GET /vitekcard_list HTTP/1.1" 200 126539
"GET /static/js/js_utils/getCookie.js HTTP/1.1" 200 500
"GET /static/js/resizebar.js HTTP/1.1" 200 789
"GET /static/js/vitek_datamap.js HTTP/1.1" 200 2172
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 200 2511
"POST /import-VITEK/ HTTP/1.1" 200 13276
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 7495
"POST /import-VITEK/ HTTP/1.1" 200 13276
"GET /static/js/importhandler.js HTTP/1.1" 200 2513
"GET /static/images/app/favicon-16x16.png HTTP/1.1" 200 489
"POST /import-VITEK/ HTTP/1.1" 200 80867
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 200 2535
"POST /import-VITEK/ HTTP/1.1" 200 12382
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 256449
"GET / HTTP/1.1" 200 6587
"POST /accounts/login/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 11234
"GET /vitekcard_list HTTP/1.1" 200 126539
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 12382
"POST /import-VITEK/ HTTP/1.1" 200 583650
"GET / HTTP/1.1" 200 6587
"GET /static/js/jquery-3.6.1.min.js HTTP/1.1" 304 0
"GET /static/js/sorting_table.js HTTP/1.1" 304 0
"GET /static/css/app.css HTTP/1.1" 304 0
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/images/brand/CO-ADD_Logo_White_NoBackground_CMYK.png HTTP/1.1" 304 0
"POST /accounts/login/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 11234
"GET /static/images/app/avatar.png HTTP/1.1" 200 9371
"GET /static/images/brand/CO-ADD_Logo_White_NoBackground_Baseline1500x375.png HTTP/1.1" 200 26975
"GET /vitekcard_list HTTP/1.1" 200 126539
"GET /static/js/resizebar.js HTTP/1.1" 200 789
"GET /static/js/js_utils/getCookie.js HTTP/1.1" 200 500
"GET /static/js/vitek_datamap.js HTTP/1.1" 200 2172
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 200 2535
"POST /import-VITEK/ HTTP/1.1" 200 12382
"POST /import-VITEK/ HTTP/1.1" 200 1092186
C:\Users\uqwzhon4\project\adjCOADD\ddrug\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\uqwzhon4\project\adjCOADD\ddrug\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 13062
C:\Users\uqwzhon4\project\adjCOADD\ddrug\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 13054
C:\Users\uqwzhon4\project\adjCOADD\ddrug\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 13054
"POST /import-VITEK/ HTTP/1.1" 200 6250
"GET /import-VITEK/ HTTP/1.1" 200 10291
"POST /import-VITEK/ HTTP/1.1" 200 13062
"GET /static/js/importhandler.js HTTP/1.1" 200 2556
"POST /import-VITEK/ HTTP/1.1" 200 5196
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 200 2529
"POST /import-VITEK/ HTTP/1.1" 200 13054
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 15710
"POST /import-VITEK/ HTTP/1.1" 200 83
"POST /import-VITEK/ HTTP/1.1" 200 136
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 304 0
C:\Users\uqwzhon4\project\adjCOADD\ddrug\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /import-VITEK/ HTTP/1.1" 200 14075
"GET /static/js/importhandler.js HTTP/1.1" 304 0
C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py changed, reloading.
Watching for file changes with StatReloader
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 13565
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 274, in post
    djID=VITEK_ID.check_from_dict(e, self.vLog)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\models.py", line 430, in check_from_dict
    valLog.add_log('Info','Update VITEK ID',f"{cDict['CARD_CODE']} ({Barcode})",'-')
  File "C:\Users\uqwzhon4\Project\adjCOADD\apputil\utils.py", line 53, in add_log
    self.Logs[logType].append(lDict)
    ~~~~~~~~~^^^^^^^^^
KeyError: 'Info'
"POST /import-VITEK/ HTTP/1.1" 500 102815
C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py changed, reloading.
Watching for file changes with StatReloader
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 304 0
C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py changed, reloading.
Watching for file changes with StatReloader
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"GET /static/images/app/favicon-16x16.png HTTP/1.1" 200 489
"POST /import-VITEK/ HTTP/1.1" 200 13062
"POST /import-VITEK/ HTTP/1.1" 200 1438
"POST /import-VITEK/ HTTP/1.1" 200 138
"GET /import-VITEK/ HTTP/1.1" 200 10291
"POST /import-VITEK/ HTTP/1.1" 200 13583
"POST /import-VITEK/ HTTP/1.1" 200 438
"POST /import-VITEK/ HTTP/1.1" 200 853
"GET /import-VITEK/ HTTP/1.1" 200 10291
"POST /import-VITEK/ HTTP/1.1" 200 13550
"POST /import-VITEK/ HTTP/1.1" 200 420
"POST /import-VITEK/ HTTP/1.1" 200 130
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 304 0
C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py changed, reloading.
Watching for file changes with StatReloader
"POST /import-VITEK/ HTTP/1.1" 200 13565
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 198
"POST /import-VITEK/ HTTP/1.1" 200 139
"GET /import-VITEK/ HTTP/1.1" 200 10291
"POST /import-VITEK/ HTTP/1.1" 200 35368
"POST /import-VITEK/ HTTP/1.1" 200 49654
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/js/importhandler.js HTTP/1.1" 200 2511
"GET / HTTP/1.1" 200 6587
"GET /static/css/custom.css HTTP/1.1" 200 12445
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 11284
"POST /accounts/login/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 11234
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /vitekcard_list HTTP/1.1" 200 126539
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/js/importhandler.js HTTP/1.1" 200 2511
"POST /import-VITEK/ HTTP/1.1" 200 25427
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 60047
"POST /import-VITEK/ HTTP/1.1" 200 586
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 13054
"POST /import-VITEK/ HTTP/1.1" 200 25172
"POST /import-VITEK/ HTTP/1.1" 200 136
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 13583
"POST /import-VITEK/ HTTP/1.1" 200 2938
"GET /static/css/custom.css HTTP/1.1" 200 12445
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/js/importhandler.js HTTP/1.1" 200 2522
"POST /import-VITEK/ HTTP/1.1" 200 13062
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 15156
"GET /import-VITEK/ HTTP/1.1" 200 10291
"GET /static/css/custom.css HTTP/1.1" 200 12445
"GET /static/js/importhandler.js HTTP/1.1" 200 2887
"POST /import-VITEK/ HTTP/1.1" 200 13174
"POST /import-VITEK/ HTTP/1.1" 200 34634
"GET /import-VITEK/ HTTP/1.1" 200 10678
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/js/importhandler.js HTTP/1.1" 200 2522
"POST /import-VITEK/ HTTP/1.1" 200 14057
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 3916
"GET /import-VITEK/ HTTP/1.1" 200 10678
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 14126
"POST /import-VITEK/ HTTP/1.1" 200 3934
"GET /import-VITEK/ HTTP/1.1" 200 10694
"GET /static/css/custom.css HTTP/1.1" 304 0
"GET /static/js/importhandler.js HTTP/1.1" 304 0
"POST /import-VITEK/ HTTP/1.1" 200 12958
"POST /import-VITEK/ HTTP/1.1" 200 20136
"POST /import-VITEK/ HTTP/1.1" 200 138
"GET /import-VITEK/ HTTP/1.1" 200 10694
"GET /static/js/importhandler.js HTTP/1.1" 304 0
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 268, in post
    self.file_report.append({key}+str(self.vLog.show()))
                            ~~~~~^~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'set' and 'str'
"POST /import-VITEK/ HTTP/1.1" 500 92970
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 269, in post
    if result_report[key]:
       ~~~~~~~~~~~~~^^^^^
KeyError: 'J.Zhong_Isolate_GN589B001P-1_N411_EUCAST_mN48NSM.pdf'
"POST /import-VITEK/ HTTP/1.1" 500 93038
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 269, in post
    if result_report[str(key)]:
       ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'J.Zhong_Isolate_GN589B001P-1_N411_EUCAST_df4MCGd.pdf'
"POST /import-VITEK/ HTTP/1.1" 500 93058
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 270, in post
    if result_report[key]:
       ~~~~~~~~~~~~~^^^^^
KeyError: 'J.Zhong_Isolate_GN589B001P-1_N411_EUCAST_ZtEDZdN.pdf'
"POST /import-VITEK/ HTTP/1.1" 500 92969
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 270, in post
    if result_report["key"]:
       ~~~~~~~~~~~~~^^^^^^^
KeyError: 'key'
"POST /import-VITEK/ HTTP/1.1" 500 92821
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 271, in post
    result_report["key"].append("Card-"+str(djCard.validStatus))
    ~~~~~~~~~~~~~^^^^^^^
KeyError: 'key'
"POST /import-VITEK/ HTTP/1.1" 500 92858
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 278, in post
    self.validate_result.append(f"{key}+CARD status: {djCard.validStatus}")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'
"POST /import-VITEK/ HTTP/1.1" 500 92964
Internal Server Error: /import-VITEK/
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Project\adjCOADD\ddrug\views.py", line 299, in post
    self.validate_result[key].append("Ast-"+str(djAst.validStatus))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'append'
"POST /import-VITEK/ HTTP/1.1" 500 93411
